### ISSUE TITLE
请问下为什么超级会员下载速度也是500KB/S

### ISSUE THREAD

**Issue by a15355447898a** [loo2k/WeiyunHelper#10]
![image](https://github.com/loo2k/WeiyunHelper/assets/62456287/f0ccb9fc-127f-4c57-971d-bedc02497bfd)
![image](https://github.com/loo2k/WeiyunHelper/assets/62456287/16b50131-e5da-4a31-ad21-6aacc795e477)

**Comment by ZIDOUZI** [comment]
连接数太小吧？我没开会员都能到4M/s以上，64连接
