### ISSUE TITLE
DDoS attack

### ISSUE THREAD

**Issue by LeeYuanao** [loo2k/WeiyunHelper#12]
I clicked on your link (http://aria2.pigfly.im/ariang/) and got a DDoS attack！！！

**Comment by WhiteButterflies** [comment]
我这边变成了成人网站

**Comment by loo2k** [comment]
感谢反馈
[http://aria2.pigfly.im/ariang/](http://aria2.pigfly.im/ariang) 已经不可用了，已经在新版本 917dc6ba8fa97f7460bfe3e35230a1d6af40a444 替换为 AriaNg 官方服务

---
Thank you for the feedback.
[http://aria2.pigfly.im/ariang/](http://aria2.pigfly.im/ariang) is no longer available, it has been replaced by the official AriaNg service in the new version 917dc6ba8fa97f7460bfe3e35230a1d6af40a444.
