### ISSUE TITLE
Aria2.me 坏了

### ISSUE THREAD

**Issue by Adjasont256** [loo2k/WeiyunHelper#7]
我今天试了一下aria2.me, 但是这个网站好像down了，我们有任何其他的方法来设置这个script吗?

**Comment by loo2k** [comment]
aria2.me 的服务已经挂掉了

前段时间 @kamingchan 把服务地址改成了 AriaNg 官方的 http://ariang.mayswind.net/ ，但是这个站点在国内的访问情况还是比较糟糕。

目前已经提供了一个自建的 [aria2.pigfly.im/ariang](http://aria2.pigfly.im/ariang/) 的服务，使用了腾讯云的 CDN 加速服务，国内的访问会更快。

https://github.com/loo2k/WeiyunHelper/blob/1156b0b5950d7c113c8d3186561f917609130004/weiyun.user.js#L59

当然也可以自己直接修改脚本中的地址，改成自己的服务。
