### ISSUE TITLE
特定的文件名出现 “指定 URL 不是 Base64 编码后的字符串! ”错误。

### ISSUE THREAD

**Issue by ngrict** [loo2k/WeiyunHelper#8]
对应文件名为：
99.9-刑事律师- 全新创作SP新的邂逅篇~电影上映前纪念~.99.9.Keiji.Senmon.Bengoshi.Kanzen.Shinsaku.SP.Aratana.Deai.Hen.Eiga.Koukaimae.Yomatsuri.SP.Chi_Jap.HDTVrip.1280X720.mp4

**Comment by loo2k** [comment]
@ngrict 可以提供分享链接和错误截图来看看

**Comment by ngrict** [comment]
分享链接 ： https://share.weiyun.com/UbozgKle
![aria2 pigfly im_ariang_](https://user-images.githubusercontent.com/14365485/149134178-8f521f7e-e94a-4879-8084-63adb4fbd8fb.png)

**Comment by loo2k** [comment]
看了下是因为通过 URL 在 AriaNg 上面创建任务的时候，传递的下载地址 base64 解码失败的原因导致的。

解码失败的原因是 base64 加密的时候会产生 `+` 和 `/` 两个字符，在 URL 中传递会被直接转义，如果希望能正常传递这两个字符则需要将 `+` 和 `/` 两个字符分辨替换为 `-` 和 `_`

而 [AriaNg 已经做了相反动作的解码](https://github.com/mayswind/AriaNg/blob/fb142ad720ff258f8bc42f28d2adcafdc9dcce57/src/scripts/controllers/command.js#L9)

参考文档
- [https://www.ietf.org/rfc/rfc4648.txt](https://www.ietf.org/rfc/rfc4648.txt)
- [angular-utf8-base64](https://github.com/munkychop/angular-utf8-base64)

**Comment by loo2k** [comment]
@ngrict 已经更新了 `0.0.8` 版本，可以安装新版本再次尝试一下
